config/routes.rb
Rails.application.routes.draw do


get '/login', to: 'sessions#new'
post '/sessions', to: 'sessions#create'
delete '/sessions', to: 'sessions#destroy'

resources :users
  get '/profile', to: 'users#show'
  get '/signup', to: 'users#new'

resources :posts do
 resources :comments, shallow: true, only:[:create, :destroy]
end
root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user
	
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  		session[:user_id] ? User.find(session[:user_id]) : nil
	end

	def authenticate_user!
	     unless current_user
	         redirect_to login_path, notice: "Please log in first."
	     end
	 end
	
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        Comment.create(body: params[:comment][:body], post: @post,)
        redirect_to @post, notice: "New Comment Created"
    end

    def destroy

    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :set_post, only: [:show, :edit, :update, :destroy, :avatar]
 before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :avatar]

 def index
  @posts = Post.last(10).reverse
  @user = User.all
 end

 def new
  @post = Post.new
 end

def edit
end

 def show
 	@user = current_user
  # @posts = Post.all
  @comment = Comment.new
 end

 def create
     @post = Post.create(posts_params)
     redirect_to @post, notice: "New post created"
 end

 def update
 		@post.update(posts_params)
 		redirect_to @post, notice: "Post updated!"
 end

 def destroy
 		@post.destroy
 		redirect_to post_path, notice: "Post deleted!"
 end

 private

	def posts_params
		params.require(:post).permit(:body, :title, :avatar, :created_at, :updated_at).merge(user: current_user)
	end

  def set_post
      @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(username: params[:username])
			if @user and @user.password == params[:password]
				session[:user_id] = @user.id
				redirect_to posts_path, notice: "Successfully logged in!"
			else
				redirect_to login_path, notice: "Login info was incorrect"
			end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/', notice: "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :profile, :edit, :destroy, :update, :avatar]
  before_action :authenticate_user!, only: [:profile, :destroy, :edit, :update, :avatar]
  before_action :authorize_user, only: [:destroy, :edit, :update]

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def show
  end

  def edit
  end

  def profile
    @user = current_user
    @posts = Post.all
    render :show
  end  

  def create
    @user = User.create(user_params)
    session[:user_id] = @user.id
    redirect_to posts_path, notice: "New account created!"
  end

  def update
    @user.update(user_params)
    redirect_to @user, notice: "Account updated!"
  end

  def destroy
  	@user.destroy
  	session[:user_id]= nil
  	redirect_to root_path, notice: "Account Deleted"
  end

  private

  def authorize_user
     unless @user == current_user
       redirect_to root_path, notice: "You do not have permission to do that."
     end 
   end

  def user_params
  	params.require(:user).permit(:username, :email, :password, :fname, :lname, :avatar)
  end

  def set_user
  	begin
  			if params[:username]
  				username = params[:username]
  				@user = User.where("lower(username) = ?", username.downcase).first
  				unless @user
  					flash[:notice] = "That user could not be found."
  					redirect_to users_path
  				end
  			else 
  				@user = User.find(params[:id])
  			end
		rescue
			flash[:notice] = "That user could not be found."
			redirect_to users_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
		session[:user_id] ? User.find(session[:user_id]) : nil
	end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="welcomecenter">
	<div id="welcome">
		<h1>Welcome to iSpy!</h1>
		<h3>Life is too funy to keep to yourself</h3>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ispy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="background">
  <header>
    <div id="logo">
      <%= image_tag("iSpy_Logo.png") %>
    </div>
    
    <div id="navBar">
      <nav>
        <div id="links">
          <%= link_to "Home", root_path %>
          <%= link_to "News Feed", posts_path %>
          <%= link_to "Users", users_path %>
          <%= link_to "iSpy", new_post_path %>

      	  <% if session[:user_id] == nil %>
      	      <%= link_to "Login", login_path %>
      	      <%= link_to "Sign Up", signup_path %>
      	  <% elsif session[:user_id] != nil %>
      	      <%= link_to current_user.username, user_path(current_user) %>
      	      <%= link_to "Logout", "/sessions", method: :delete %>
      	  <% end %>
        </div>
      </nav>
    </div>

   </header>

    <div id="loginSignup">
      <% if session[:user_id] == nil %>
        <h1>Please login or sign up for iSpy</h1>
      <% end %>
    </div>

    <% if flash[:notice] %>
     <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    
  <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="form-style-6"> 

<%= form_for @post, html: { multipart: true } do |f| %>
	<p><%= f.label :title, "Upload an Image" %>
		<%= f.file_field :avatar, required: true %>
	</p>
  <p><%= f.label :title %><br>
      <%= f.text_field :title %>
  </p>

  <p><%= f.label :body %><br>
      <%= f.text_area :body, style:"width: 283px;", rows: 10, col: 50 %>
  </p>

  <p><%= f.submit %></p>
<% end %>

</div>

app/views/posts/_post.html.erb
<div class="tile">
   
 <div class="container">
     <div class="tileContentTop">
         <h3>@<%= link_to post.user.username, user_path(post.user_id) %></h3>
     </div>
     
     <div class="tileImage">
         <%= link_to (image_tag post.avatar.url(:medium)),post %>
     </div>

     <div class="tileContent">
         <h4><%= post.title %></h4>
         <p><%= post.body %></p>
     </div>

     <div class="editPost">
         <%if current_user and current_user.id == post.user_id %>
         <%= link_to 'Edit Post', edit_post_path(post) %>
         <%end%>
     </div> 

     <div class="postTimeInfo">
         <div class="postCreateTime">
             <% if 1 < Time.now.day - post.updated_at.day %>
             <h6>Created <%= t= Time.now.day - post.updated_at.day%> days ago </h4>
             <% else %>
             <h6>Created <%= Time.now.day - post.updated_at.day%> day ago </h4>    
             <% end %>
         </div>

         <div class="postUpdateTime">
             <% if post.updated_at != post.created_at %>
             <h6>Updated <%= Time.now.day - post.updated_at.day%> days ago </h4>
             <% end %>
         </div>
     </div>       

 </div>

</div>

app/views/posts/edit.html.erb
<div class="newPost">
  <h1>Edit Post</h1>
  <%= form_for @post, html: { multipart: true } do |f| %>
  	<p><%= f.label :title, "Upload an Image" %>
  		<%= f.file_field :avatar %>
  	</p>
    <p><%= f.label :title %><br>
        <%= f.text_field :title %>
    </p>

    <p><%= f.label :body %><br>
        <%= f.text_area :body, style:"width: 283px;", rows: 10, col: 50 %>
    </p>

    <p><%= f.submit %></p>
  <% end %>
  <div class="cancelbutton"> <%= link_to 'cancel', posts_path %> </div>
</div>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/new.html.erb
<div class="newPost">
	<h1>New Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="masterside">

	<div class="sidebar">

			<div class="bio">

				<div class="bioTop">
					<p><%= @post.user.username %></p>
				</div>

				<div class="bioBottom">
					<p><%= @post.user.fname %></p>
					<p><%= @post.user.lname %></p>
					<p><%= @post.user.email %></p>
				</div>

			</div>

	</div>

</div>

<div class="main">

	<div class="container">
		
		<%= render @post %>

	</div>

<div class="comments">
	<% if current_user != nil %>
	<h3>New Comment</h3>
	<%= form_for [@post, @comment] do |f| %>
	   <%= f.text_area :body, style:"width: 283px;", rows: 10, col: 50 %><br>
	   <%= f.submit %>
	<%end%>
	<% end %>


	<h3>Comments</h3>
	<% @post.comments.reverse.each do |comment| %>
	    <p><%= comment.body %></p>
	    <hr>
	<% end %>
</div>	

</div>	

app/views/users/_form.html.erb
<div class="form-style-6">

	<%= form_for @user do |f| %>
		
		<p>
			<%= f.label :fname, "First Name" %>
			<%= f.text_field :fname %>
		</p>

		<p>
			<%= f.label :lname, "Last Name" %>
			<%= f.text_field :lname %>
		</p>

		<% if @user.new_record?%>
		<p>
			<%= f.label :password %>
			<%= f.password_field :password %>
		</p>
		<% end %>

		<p>
			<%= f.label :username %>
			<%= f.text_field :username %>
		</p>

		<p>
			<%= f.label :email %><br>
			<%= f.email_field :email %>
		</p>

		<p>
			<%= f.submit @user.new_record? ? "sign up" : "edit account"%>
		</p>
	<%end%>
</div>

app/views/users/_post.html.erb
<div class="tile">
	
	<div class="container">
		<div class="tileContentTop">
			<h3>@<%= link_to post.user.username, post %></h3>
		</div>
		
		<div class="tileImage">
			<%= image_tag post.avatar.url(:medium) %>
		</div>

		<div class="tileContent">
			<h4><%= post.title %></h4>
			<p><%= post.body %></p>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Edit Your Account!</h1>
<%= render 'form' %>

app/views/users/index.html.erb
	
	<% @users.each do |user| %>
	<div class="userInfo">	
		<div class="userTile">
			<h3 class="username">@<%= link_to user.username, user_path(user.id)%></h3>
			<p>Name: <%= user.fname %> <%= user.lname %></p>
			<p>Email: <%= user.email %></p>
		</div>
	</div>
	<%end%>

app/views/users/new.html.erb
<div class="newPost">
	<h1>Sign Up!</h1>
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="masterside">

	<div class="sidebar">

			<div class="bio">

				<div class="bioTop">
					<h3 class="username">@<%= @user.username %></h3>
				</div>

				<div class="bioBottom">
					<p>Name: <%= @user.fname %> <%= @user.lname %></p>
					<p>Email: <%= @user.email %></p>
				</div>

			</div>

	</div>

</div>

<div class="main">

	<div class="container">
		
		<%= render @user.posts %>

	</div>

</div>	